### ISSUE TITLE
TTS strings not updating in Player Main Panel

### ISSUE THREAD

**Issue by jmwhite5** [simplextech/udi-poly-sonoscontroller#3]
I'm pretty excited about the ability to announce (alerts, notification, etc...) using the Sonos Controller.  I was able to configure 1 string (SAY_TTS-1) and it appears correctly in the player panel list.

However, the second string does not get updated in the UI panel.   It keeps saying "empty", but it actually works.  I can get the system to utter my new string.  

You can see a picture of the panel here [https://forum.universal-devices.com/topic/31057-tts-strings-not-updating-in-player-main-panel/].

**Comment by simplextech** [comment]
I replied to the forum post.  After the re-discover or NodeServer restart and restarting the Admin Console if that doesn't resolve it let me know.  The Admin Console doesn't updates new parameters dynamically and requires a restart.  The new configuration isn't available without updating the "profile" from the Admin Console main SonosController node has the update profile and re-discover.  The re-discover will check for new everything and update the profile.  Admin Console restart is always necessary though.  

If this resolves it please close the ticket.  If not let me know.

**Comment by jmwhite5** [comment]
Oh, that worked.  Thanks.  Could the Re-Discover and Update Profiles be combined?  I may have hit one or the other in my previous attempts, but this time I hit both (does the order matter?).   Thanks for a super useful piece of functionality.  Closing as this solved my problem and it seems like the solution is with the Admin Console.
